### PR TITLE
Add drag-in box for quickly setting (arbitrary) bones in Armature Link

### PR DESCRIPTION
**Pull request by nullstalgia**
And since I know you don't want people hard-coding normal Humanoid bones if they use this, I have it check if the bone supplied matches the Avatar's layout.

I wasn't able to think of a way to just get a list of all the humanoid bones as GameObjects to check against instead, but I found this to be decent enough.

I placed it just under the "Path to bone on avatar" field, but if you think the check is robust enough/gets improved, we could maybe place it just under the "Link to" dropdown?

```
The changes made in this contribution are free and unencumbered software
released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
```

### CODE REVIEW

**Comment by nullstalgia** [comment]
I pulled the string option and the drag target box out of the Advanced Options field while I setting up a prop with a lot of parts to re-parent, and found it really convenient. 

The only reason I also pulled out the string field, was in case a user accidentally drags in the wrong bone, they don't have to go into an "Advanced" field to fix it.

Feel free to tell me to revert this, I just wanted to experiment a little and also see what you think of it?

**Comment by SenkyDragon** [comment]
Can you copy the unlicense from https://github.com/VRCFury/VRCFury/blob/main/com.vrcfury.vrcfury/CONTRIBUTING.md into this PR?

**Comment by nullstalgia** [comment]
@SenkyDragon That look good?

**Comment by nullstalgia** [comment]
https://github.com/VRCFury/VRCFury/assets/20761757/f2f1e9fa-8ca0-480f-a9a7-5ee149e85e3e

Stole the functionality from #157 (with permission from @TayouVR ❤️ ), the drag-in box is now a smart cookie! Trying to make a given path as generic as possible.

**Comment by TayouVR** [comment]
@SenkyDragon please have a look at this, it has been months

**Pull request merged**
