### PR TITLE
rewrite Build in PlayMode with Awake for better & simpler compatibility with Av3Emu and GestureManager

### PR DESCRIPTION
**Pull request by anatawa12**
On the Av3Emu dev discord, we hear not working well with VRCFury. 
I assume the reason why not working is restarting av3emulator in VRCFury is not working well.

To improve compatibility, I rewrite way to boot Av3Emu with Awake.
The Awake method is used in many non destructive tools such as AvatarOptimizer (until v1.0.x) or ModularAvatar.

This method is compatible with both Av3Emu and (latest) GestureManager.

### CODE REVIEW

**Comment by SenkyDragon** [comment]
Thank you for the very comprehensive MR! I agree this approach is much more reasonable than what we currently have.

A few nits:
* We need to keep RestartAudiolink, because they call `Shader.SetGlobalTexture` when their component starts, which injects the audiolink texture into every currently-loaded material. Since VRCFury may create new materials, it needs to do it again so the new mats also receive the texture.
* Add yourself to the CONTRIBUTING.md
* Please paste the block of text from the CONTRIBUTING.md into this merge request as a comment

**Comment by anatawa12** [comment]
```
The changes made in this contribution are free and unencumbered software
released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
```

**Comment by SenkyDragon** [comment]
Unfortunately this doesn't seem to be usable. I've been testing and poking at it for quite a while, but performing asset changes within Awake just crashes unity way too often. In many of my projects, it crashes 100% of the time while entering play mode.

image

This first error is caused by calling AssetDatabase.SaveAssets(); within Awake, which is avoidable, but even without that, the build still reliably fails with:

image

**Comment by anatawa12** [comment]
I replaced the apply/build on play way with AAO's new method which I believe it's stabler than Awake but not widely used.
Is this work well?

**Comment by SenkyDragon** [comment]
With the latest commit, VRCFury now runs after AV3emulator initializes, which defeats the purpose.

**Comment by SenkyDragon** [comment]
We sort of seem to be stuck in a corner, because Av3emulator initializes during Awake, and the scene isn't initialized enough at that point to support the asset changes that VRCFury requires.

**Comment by lyuma** [comment]
From what I understand, the whole issue stems from the fact that Av3Emulator is using Awake to initialize. Does Av3Emulator need to move later? If so, when? Is it within the first frame?

Is the crash caused by `AssetDatabase.SaveAssets()` - I'm skeptical about the need for VRCFury to perform global 
operations with AssetDatabase, since setting individual properties on SerializedObject should be safe - For example, if you look at modular avatar, it does not do this, and it seems to work fine the way it was invoked.
https://github.com/search?q=repo%3Abdunderscore%2Fmodular-avatar%20assetdatabase&type=code

**Comment by anatawa12** [comment]
Actually, modular avatar does `AssetDatabase.SaveAssets()` in Awake so I think saving some specific types of assets will cause editor crash.

https://github.com/bdunderscore/modular-avatar/blob/176e79213736a193207a1615762f4058eabd887f/Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs#L275

> If so, when? Is it within the first frame?

VRCFury's previous implementation & current implementation in this PR (964c5684b24cf90ffa690f1a333febaa3c392150) does initialization in scene load process so I think in `Start`, in other words, first frame, is good place.

**Comment by SenkyDragon** [comment]
Start() seems appropriate, however it still needs to load before vrchat's runtime components load, otherwise they'll record the wrong physbone offsets, and find the wrong contact/physbone parameters on the controllers.

**Comment by SenkyDragon** [comment]
Thanks for the continuing efforts toward fixing this issue. In https://github.com/VRCFury/VRCFury/commit/16f834a7f931fd9afa19d799ab0da02ef46d4ed5 , VRCFury now plays nice with any emulators assuming they initiate in Start() or later. For now it will continue restarting Av3emu after building, but if Av3emu switches to loading in Start(), VRCF will automatically stop restarting it (the restart only happens if it finds an existing av3emu runtime on the avatar). I've add you all to the credits in CONTRIBUTING.md for the assistance.

**Pull request closed without merging**
